name: Clang Format


on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest Clang-Format
        run: |
          sudo apt update
          sudo apt install -y clang-format

      - name: Run Check Clang-Format
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" \) -exec clang-format -i {} --dry-run -Werror +
          
