name: Clang Format


on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest Clang-Format
        run: |
          sudo apt update
          sudo apt install -y clang-format

      - name: Find source files
        id: find_files
        run: |
          FILES=$(git ls-files '*.c' '*.cc' '*.cpp' '*.h' '*.hpp' '*.cxx' '*.hh' '*.hxx')
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Run clang-format check
        if: env.FILES != ''
        run: |
          echo "Checking code format with clang-format..."
          clang-format --version
          echo "$FILES" | tr ' ' '\n' | xargs clang-format -style=file --dry-run -Werror
          
